### ISSUE TITLE
I can't run the node. I get this error

### ISSUE THREAD

**Issue by midoranode** [aura-nw/testnets#1]
![Screenshot_10](https://user-images.githubusercontent.com/104720231/171382602-68f156e0-7415-40d7-88f7-e07e40bd94bc.png)

**Comment by kienvc** [comment]
Have you replaced the genesis file by the one in **halo-testnet-001** directory ?

**Comment by Amidomaruu** [comment]
> Have you replaced the genesis file by the one in **halo-testnet-001** directory ?

Yes, I downloaded it and replaced. From this link
https://github.com/aura-nw/testnets/blob/main/halo-testnet-001/genesis.json

**Comment by midoranode** [comment]
I did all with genesis file and nothing changed. But when I try to run node on another server, It stated. Problem has gone
